### ISSUE TITLE
Cw#1

### ISSUE THREAD

**Issue by Nowocinski** [Nowocinski/Zaawansowane-programowanie-obiektowe#1]

**Comment by pjastr** [comment]
Drobne uwagi:

A2,A3 - lepszy byłby typ `int`
A11 - powinno być na odwrót - duże na małe.
A12 - algorytm nie jest w pełni poprawny

np. dla
Wprowadź tekst: 3455 f fff gg
Najdłuższe słowo to: ffffgg

Sprawdziłem na razie do A20.

**Comment by pjastr** [comment]
Przepraszam, ale sprawdziłem dosyć pobieżnie programy. Ogólnie błędów nie ma

A44 - przy dzieleniu `2*a` musi być w nawiasie
